export enum EApiEndpointNames {
  POSTUserSendOtp = 'send-otp',
  POSTUserCheckOtp = 'check-otp',
  POSTSupplierSignup = 'signup',
  POSTSupplierSendOtp = 'send-otp',
  POSTSupplierCheckOtp = 'check-otp',
  POSTSupplierSupplementaryInformation = 'supplementary-information',
  PUTSupplierUploadDocuments = 'upload-documents',
  PUTSupplierUploadContract = 'upload-contract',
  POSTCreateCategory = '',
  GETCategories = '',
  GETCategoryBySlug = 'by-slug/:slug',
  PATCHUpdateCategory = ':id',
  DELETECategory = ':id',
  POSTCreateMenu = '',
  GETMenusBySupplierId = 'get-menu-by-supplier-id/:supplierId',
  POSTCreateMenuGroup = '',
  GETMenuGroups = '',
  GETMenuGroup = ':id',
  PUTUpdateMenuGroup = ':id',
  DELETEMenuGroup = ':id',
}
